- name: build hosts file
  sudo: true
  lineinfile: dest=/etc/hosts regexp='.*{{ item.name }}$'
              line="{{ item.address }} {{ item.name }}"
              state=present
  with_items: hosts
